/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.latihanprakikum9;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author user
 */
public class TambahDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form TambahDataPanel
     */
    // menampung data mahasiswa
    private Mahasiswa mahasiswaToUpdate;
    
    public TambahDataPanel() {
        initComponents();
        this.mahasiswaToUpdate = null;
        
        buttonGroup1.add(lakiLakiRadioButton);
        buttonGroup1.add(perempuanRadioButton);
    }
    
    public TambahDataPanel(Mahasiswa mhs){
        this(); //this initComponents
        
        this.mahasiswaToUpdate = mhs;
        
        namaTextField.setText(mhs.getNama());
        nimTextField.setText(mhs.getNim());
        nimTextField.setEditable(false); // NIM tidak boleh diubah saat update
        prodiComboBox.setSelectedItem(mhs.getProdi());
        
        if (mhs.getJenisKelamin().equals("Laki-Laki")) {
            lakiLakiRadioButton.setSelected(true);
        } else {
            perempuanRadioButton.setSelected(true);
        }
        
        aktifCheckBox.setSelected(mhs.isActive());
        
        // Ubah teks UI
        jLabel1.setText("Update Data Mahasiswa");
        kirimButton.setText("Update");
    }
    
    private void clearForm(){
        namaTextField.setText("");
        nimTextField.setText("");
        lakiLakiRadioButton.setSelected(false);
        perempuanRadioButton.setSelected(false);
        aktifCheckBox.setSelected(false);
    }
    
    // validasi NIM
    private boolean isNimExists(String nim) {
        for (Mahasiswa mhs : Mahasiswa.mahasiswas) {
            if (mhs.getNim().equals(nim)) {
                return true;
            }
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        nimTextField = new javax.swing.JTextField();
        prodiComboBox = new javax.swing.JComboBox<>();
        lakiLakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        aktifCheckBox = new javax.swing.JCheckBox();
        kirimButton = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jLabel1.setText("Tambah Data Mahasiswa");

        jLabel2.setText("Nama");

        jLabel3.setText("NIM");

        jLabel4.setText("Prodi");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Status");

        namaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextFieldActionPerformed(evt);
            }
        });

        nimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimTextFieldActionPerformed(evt);
            }
        });

        prodiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 Teknik Informatika", "S1 Teknik Elektro", " " }));

        lakiLakiRadioButton.setText("Laki-Laki");
        lakiLakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiLakiRadioButtonActionPerformed(evt);
            }
        });

        perempuanRadioButton.setText("Perempuan");

        aktifCheckBox.setText("Aktif");

        kirimButton.setBackground(new java.awt.Color(0, 255, 255));
        kirimButton.setText("Kirim");
        kirimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aktifCheckBox)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lakiLakiRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(perempuanRadioButton))
                            .addComponent(kirimButton)
                            .addComponent(namaTextField)
                            .addComponent(nimTextField)
                            .addComponent(prodiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(prodiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lakiLakiRadioButton)
                    .addComponent(perempuanRadioButton))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(aktifCheckBox))
                .addGap(30, 30, 30)
                .addComponent(kirimButton)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void kirimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimButtonActionPerformed
        String nama = namaTextField.getText();
        String nim = nimTextField.getText();
        String prodi = (String) prodiComboBox.getSelectedItem();
        
        // 1. Validasi string kosong
        if (nama.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (nim.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NIM tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 2. Validasi NIM harus angka
        if (!nim.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "NIM harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 3. Validasi jenis kelamin
        String jenisKelamin = null;
        if (lakiLakiRadioButton.isSelected()) {
            jenisKelamin = "Laki-Laki";
        } else if (perempuanRadioButton.isSelected()) {
            jenisKelamin = "Perempuan";
        } else {
            JOptionPane.showMessageDialog(this, "Jenis kelamin harus dipilih!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        boolean isActive = aktifCheckBox.isSelected();
        // --- AKHIR VALIDASI ---

        // Cek apakah ini mode "Update" atau "Create"
        if (mahasiswaToUpdate != null) {
            // --- LOGIKA UPDATE ---
            // Set data baru ke objek mahasiswa yang sudah ada
            mahasiswaToUpdate.setNama(nama);
            mahasiswaToUpdate.setProdi(prodi);
            mahasiswaToUpdate.setJenisKelamin(jenisKelamin);
            mahasiswaToUpdate.setActive(isActive);
            // NIM tidak di-set karena tidak boleh diubah
            
            JOptionPane.showMessageDialog(this, "Sukses memperbarui data mahasiswa " + nama);
            
            // Kembali ke panel LihatDataPanel
            MainJFrame parentFrame = (MainJFrame) SwingUtilities.getWindowAncestor(this);
            if (parentFrame != null) {
                parentFrame.changeMainPanel(new LihatDataPanel());
            }
            
        } else {
            // --- LOGIKA CREATE ---
            
            // 4. Validasi NIM duplikat (hanya saat create)
            if (isNimExists(nim)) {
                JOptionPane.showMessageDialog(this, "NIM " + nim + " sudah terdaftar!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Buat objek baru jika semua validasi lolos
            Mahasiswa mahasiswa = new Mahasiswa(nama, nim, prodi, jenisKelamin, isActive);
            Mahasiswa.mahasiswas.add(mahasiswa);

            JOptionPane.showMessageDialog(this, "Sukses menambahkan data mahasiswa " + nama);
            clearForm();
        }
    }//GEN-LAST:event_kirimButtonActionPerformed

    private void lakiLakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiLakiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiLakiRadioButtonActionPerformed

    private void nimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimTextFieldActionPerformed

    private void namaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aktifCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kirimButton;
    private javax.swing.JRadioButton lakiLakiRadioButton;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JComboBox<String> prodiComboBox;
    // End of variables declaration//GEN-END:variables
}
