<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.kedaikasir</groupId>
    <artifactId>SistemKasirKedai</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>24</maven.compiler.release>
        <exec.mainClass>com.kedaikasir.sistemkasirkedai.SistemKasirKedai</exec.mainClass>
    </properties>
    <dependencies>
    <!-- Dependensi untuk FlatLaf (Modern Look and Feel) -->
    <dependency>
        <groupId>com.formdev</groupId>
        <artifactId>flatlaf</artifactId>
        <version>3.4.1</version> 
        <!-- Anda bisa cek versi terbaru di Maven Central -->
    </dependency>
    </dependencies>

</project>